year: 2024
season: "下半季"
id: MMCL
bloodline: "gon-color王翦LG7.3*遊鬼MDA.M44S"
generation: "F1"
name: 中國大鍬
scientific_name: Dorcus hopei hopei
size: 64.5
tooth: 5.9
description: "gon-color王翦LG7.3*遊鬼MDA.M44S"
images:
  - main.jpg
  - 01.jpg