year: 2023
season: "下半季"
id: A1-747 (a04)
bloodline: "觀蟲A-line"
generation: "CBF1"
name: 中國大鍬
scientific_name: Dorcus hopei hopei
size: 74
tooth: 7.47
description: "極太短厚特化型，大顎基部極為粗壯，完美遺傳了親代的寬度。"
images:
  - main.jpg
  - 01.jpg
  - 02.jpg
  - 03.jpg
  - 04.jpg
  - 05.jpg