year: 2025
season: "下半季"
id: 25D163♂
bloodline: "(qwe169*FF-FF136)x(0F136FOX*FFFOX)"
generation: "CBF1"
name: 長戟大兜原名亞種
scientific_name: Dynastes hercules hercules
size: 153
tooth: 
description: "我希望延續「觀蟲」一貫的審美標準，
              朝向 極太、壯碩且兼具美感 的方向篩選。
              第一隻
              第一眼 就被他筆直的胸角吸引，
              雖然頭角略有側彎，但胸角直挺、整體粗度均勻，
              正好符合我對長戟體態的偏好。"
images:
  - main.jpg
  - 01.jpg
  - 02.jpg
  - 03.jpg