year: 2025
season: "下半季"
id: 25B154♂
bloodline: "FF-FF136河野本家"
generation: "CBF4"
name: 長戟大兜原名亞種
scientific_name: Dynastes hercules hercules
size: 154
tooth: 
description: "第二隻
              在角型與比例上，滿足了我們對長戟的多項審美。

              胸角筆直挺拔，
              角型乾淨、無倒勾、無折角，
              也沒有前段偏窄、基部膨大的三角型走勢，
              砲管型胸角粗細過渡自然、勻稱，線條相當漂亮。

              頭角呈現片狀、寬大，
              在視覺上與胸角形成良好的比例平衡，
              讓體態看起來更顯厚實。"
images:
  - main.jpg
  - 01.jpg
  - 02.jpg