year: 2024
season: "下半季"
id: Q7
bloodline: "日血"
generation: "CBF1"
name: 中國大鍬
scientific_name: Dorcus hopei hopei
size: 75.2
tooth: 7.1
description: "同批爆翅率高"
images:
  - main.jpg
  - 01.jpg