year: 2024
season: "下半季"
id: W732 (王翦本ライン系 x GX50-T24)
bloodline: "王翦本ライン系 x GX50-T24"
generation: "F2"
name: 中國大鍬
scientific_name: Dorcus hopei hopei
size: 71.5
tooth: 7.32
description: "♂　71.5mm 
              頭28.0mm胸28.8mm
              顎幅L7.24/R7.32

              頭幅比39.1%（非常噁心的數據）
              顎幅比10.1-10.2%
              2023/10/14測量數值

              血統：王翦本ライン系 x GX50-T24
              出品者：遊鬼yuki 先生

              後言：
              今年的最後一隻補強種公
              蟄伏了三個月
              怕天氣越來越冷會睡死
              先請出來活動一下 "
images:
  - main.jpg
  - 01.jpg
  - 02.jpg
  - 03.jpg
  - 04.jpg
  - 05.jpg