year: 2024
season: "下半季"
id: 84G
bloodline: "觀蟲純血"
generation: "CBF1"
name: 中國大鍬
scientific_name: Dorcus hopei hopei
size: 72.5
tooth: 6.85
description: "極太短厚特化型，大顎基部極為粗壯，完美遺傳了親代的寬度。"
images:
  - main.jpg
  - 01.jpg