year: 2025
season: "下半季"
id: 25C157♂
bloodline: "FF-FF136河野本家"
generation: "CBF4"
name: 長戟大兜原名亞種
scientific_name: Dynastes hercules hercules
size: 157
tooth: 
description: "第三隻
              大概是我們這批最粗的個體了吧！
              胸角同樣挺拔、無倒勾、無折角，
              目前順利過蟄伏，已經準備好粗血的母蟲等他發力💪"
images:
  - main.jpg
  - 01.jpg
  - 02.jpg
  - 03.jpg